# Generated by Django 4.2.4 on 2023-08-22 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=30, verbose_name='Название букета')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Список букетов',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ColorSpectrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_spectrum', models.CharField(default='Какой-то цвет', max_length=50, verbose_name='Цветовая гамма')),
            ],
            options={
                'verbose_name': 'Цветовая гамма',
                'verbose_name_plural': 'Цветовые гаммы',
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=30, verbose_name='Телефон клиента')),
                ('status', models.IntegerField(choices=[(1, 'В ожидании'), (2, 'Принято'), (3, 'Исполнено')], verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка на консультацию',
                'verbose_name_plural': 'Заявки на консультацию',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=50)),
                ('path', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20, verbose_name='Телеграмм id')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Имя клиента')),
                ('phone', models.CharField(default='', max_length=30, verbose_name='Номер клиента')),
                ('address', models.CharField(default='', max_length=300, verbose_name='Адрес клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField(default=datetime.date.today, verbose_name='Дата исполнения')),
                ('status', models.IntegerField(choices=[(1, 'Принят'), (2, 'Готовиться'), (3, 'Доставка')], verbose_name='Статус заказа')),
                ('comment', models.TextField(default='', max_length=300, verbose_name='Комментарий к заказу')),
                ('delivery_address', models.CharField(default='', max_length=250, verbose_name='Адрес доставки')),
                ('all_price', models.IntegerField(default=0, verbose_name='Общая стоимость')),
                ('bouquet_id', models.ManyToManyField(to='flowers_app.bouquets', verbose_name='Готовые букеты')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers_app.telegramuser', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='bouquets',
            name='category',
            field=models.ManyToManyField(to='flowers_app.categories', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='bouquets',
            name='color_spectrum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers_app.colorspectrum', verbose_name='Цветовая гамма'),
        ),
        migrations.AddField(
            model_name='bouquets',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers_app.images', verbose_name='Картинка'),
        ),
    ]
