# Generated by Django 4.2.4 on 2023-08-23 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='bouquet_id',
            field=models.ManyToManyField(blank=True, to='flowers_app.bouquets', verbose_name='Готовые букеты'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='execution_date',
            field=models.CharField(default=datetime.date.today, max_length=30, verbose_name='Дата исполнения'),
        ),
    ]
