# Generated by Django 4.2.4 on 2023-08-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='bouquets',
        ),
        migrations.CreateModel(
            name='ProductsBouquets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bouquets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers_app.bouquets', verbose_name='Букет')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers_app.products', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Позиция - букет',
                'verbose_name_plural': 'Позиции - букет',
            },
        ),
    ]
