# Generated by Django 4.2.4 on 2023-08-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_app', '0002_alter_orders_bouquet_id_alter_orders_execution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
