# Generated by Django 4.2.4 on 2023-08-22 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_app', '0002_remove_products_bouquets_productsbouquets'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='bouquets',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers_app.bouquets'),
        ),
    ]
