# Generated by Django 4.2.4 on 2023-08-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_app', '0003_productinorder_bouquets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers_app.images', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Наименование'),
        ),
    ]
